# 错误处理

*错误处理* 是指 Express 如何捕获和处理同步和异步发生的错误。Express 默认提供了错误处理程序，因此您无需编写自己的错误处理程序即可开始使用。

## 捕获错误

确保 Express 捕获在运行路由处理程序和中间件期间发生的所有错误是很重要的。

同步代码中发生的错误在路由处理程序和中间件内部不需要额外的工作。如果同步代码抛出错误，Express 将会捕获和处理它。例如：

```javascript
app.get('/', function (req, res) {
  throw new Error('BROKEN') // Express 会自行捕获这个错误。
})
```

对于从路由处理程序和中间件调用的异步函数返回的错误，您必须将它们传递给 `next()` 函数，Express 将会捕获和处理它们。例如：

```javascript
app.get('/', function (req, res, next) {
  fs.readFile('/file-does-not-exist', function (err, data) {
    if (err) {
      next(err) // 将错误传递给 Express。
    } else {
      res.send(data)
    }
  })
})
```

从 Express 5 开始，当路由处理程序和中间件返回一个 Promise 时，如果它们拒绝或抛出错误，将会自动调用 `next(value)`。例如：

```javascript
app.get('/user/:id', async function (req, res, next) {
  var user = await getUserById(req.params.id)
  res.send(user)
})
```

如果 `getUserById` 抛出错误或拒绝，`next` 将会被调用，传递抛出的错误或拒绝的值。如果未提供拒绝的值，`next` 将会被调用，并使用 Express 路由器提供的默认错误对象。

如果您将任何内容传递给 `next()` 函数（除了字符串 `'route'`），Express 将视当前请求为错误，并跳过任何剩余的非错误处理路由和中间件函数。

如果在一个序列的回调中没有提供数据，只有错误，您可以简化这段代码如下：

```javascript
app.get('/', [
  function (req, res, next) {
    fs.writeFile('/inaccessible-path', 'data', next)
  },
  function (req, res) {
    res.send('OK')
  }
])
```

在上面的示例中，`next` 被作为 `fs.writeFile` 的回调提供，无论是否有错误都会被调用。如果没有错误，则执行第二个处理程序；否则，Express 会捕获并处理错误。

必须捕获由路由处理程序或中间件调用的异步代码中发生的错误，并将它们传递给 Express 进行处理。例如：

```javascript
app.get('/', function (req, res, next) {
  setTimeout(function () {
    try {
      throw new Error('BROKEN')
    } catch (err) {
      next(err)
    }
  }, 100)
})
```

上面的示例使用了 `try...catch` 块来捕获异步代码中的错误，并将它们传递给 Express。如果省略了 `try...catch` 块，Express 将不会捕获错误，因为它不是同步处理程序代码的一部分。

使用 Promises 可以避免 `try...catch` 块的开销，或者在使用返回 Promises 的函数时使用。例如：

```javascript
app.get('/', function (req, res, next) {
  Promise.resolve().then(function () {
    throw new Error('BROKEN')
  }).catch(next) // 错误将会传递给 Express。
})
```

由于 Promises 自动捕获同步错误和拒绝的 Promises，因此您可以简单地将 `next` 作为最终的 catch 处理程序，Express 将会捕获错误，因为 catch 处理程序将错误作为第一个参数。

您还可以使用一系列处理程序来依赖于同步错误捕获，将异步代码简化为一些微不足道的内容。例如：

```javascript
app.get('/', [
  function (req, res, next) {
    fs.readFile('/maybe-valid-file', 'utf-8', function (err, data) {
      res.locals.data = data
      next(err)
    })
  },
  function (req, res) {
    res.locals.data = res.locals.data.split(',')[1]
    res.send(res.locals.data)
  }
])
```

上面的示例从 `readFile` 调用中提取了几个微不足道的语句。如果 `readFile` 引发错误，则将错误传递给 Express，否则您将迅速返回到链中的下一个处理程序中的同步错误处理领域。然后，上面的示例尝试处理数据。如果失败，则同步错误处理程序将捕获它。如果您在 `readFile` 回调内部执行此处理，则应用程序可能会退出，Express 错误处理程序将不会运行。

无论使用哪种方法，如果您希望 Express 错误处理程序被调用并且应用程序继续运行，您必须确保 Express 接收到错误。

## 默认错误处理程序

Express 自带了一个内置的错误处理程序，用于处理应用中可能遇到的任何错误。这个默认的错误处理中间件函数被添加到中间件函数栈的末尾。

如果将错误传递给 `next()`，并且您没有在自定义错误处理程序中处理它，它将由内置的错误处理程序处理；错误将被写入客户端，并附带堆栈跟踪。在生产环境中，堆栈跟踪不会包含在内。

将环境变量 `NODE_ENV` 设置为 `production`，以在生产模式下运行应用程序。

当写入错误时，以下信息将添加到响应中：

- `res.statusCode` 从 `err.status`（或 `err.statusCode`）

设置。如果该值超出 4xx 或 5xx 范围，将会被设置为 500。
- `res.statusMessage` 根据状态码设置。
- 在生产环境中，响应的主体将是状态码消息的 HTML，否则将是 `err.stack`。
- 在一个 `err.headers` 对象中指定的任何标头。

如果在开始写入响应后（例如，在将响应流式传输给客户端时）通过 `next()` 调用错误，Express 默认的错误处理程序将关闭连接并失败请求。

因此，当添加自定义错误处理程序时，您必须在头部已经发送到客户端时委托给默认的 Express 错误处理程序：

```javascript
function errorHandler (err, req, res, next) {
  if (res.headersSent) {
    return next(err)
  }
  res.status(500)
  res.render('error', { error: err })
}
```

请注意，如果在代码中多次使用 `next()` 调用错误，则默认错误处理程序可能会被触发，即使存在自定义错误处理中间件。

## 编写错误处理程序

与其他中间件函数一样，可以按照相同的方式定义错误处理中间件函数，只是错误处理函数有四个参数，而不是三个：`(err, req, res, next)`。例如：

```javascript
app.use(function (err, req, res, next) {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
```

您可以在最后定义错误处理中间件，放在其他的 `app.use()` 和路由调用之后。例如：

```javascript
var bodyParser = require('body-parser')
var methodOverride = require('method-override')

app.use(bodyParser.urlencoded({
  extended: true
}))
app.use(bodyParser.json())
app.use(methodOverride())
app.use(function (err, req, res, next) {
  // 逻辑
})
```

在中间件函数内部的响应可以是任何格式，例如 HTML 错误页面、简单消息或 JSON 字符串。

出于组织（和更高级的框架）目的，您可以定义多个错误处理中间件函数，就像您对常规中间件函数所做的那样。例如，要为使用 `XHR` 和不使用 `XHR` 的请求定义错误处理程序：

```javascript
var bodyParser = require('body-parser')
var methodOverride = require('method-override')

app.use(bodyParser.urlencoded({
  extended: true
}))
app.use(bodyParser.json())
app.use(methodOverride())
app.use(logErrors)
app.use(clientErrorHandler)
app.use(errorHandler)
```

在这个示例中，通用的 `logErrors` 可能会将请求和错误信息写入到 `stderr`，例如：

```javascript
function logErrors (err, req, res, next) {
  console.error(err.stack)
  next(err)
}
```

同样在这个示例中，`clientErrorHandler` 被定义如下；在这种情况下，错误被明确地传递给下一个处理程序。

请注意，在错误处理函数中不调用“next”时，您负责编写（并结束）响应。否则，这些请求将会“挂起”，并且不会被垃圾回收。

```javascript
function clientErrorHandler (err, req, res, next) {
  if (req.xhr) {
    res.status(500).send({ error: 'Something failed!' })
  } else {
    next(err)
  }
}
```

将“catch-all” `errorHandler` 函数实现如下（例如）：

```javascript
function errorHandler (err, req, res, next) {
  res.status(500)
  res.render('error', { error: err })
}
```

如果您的路由处理程序具有多个回调函数，您可以使用 `route` 参数跳过到下一个路由处理程序。例如：

```javascript
app.get('/a_route_behind_paywall',
  function checkIfPaidSubscriber (req, res, next) {
    if (!req.user.hasPaid) {
      // 继续处理这个请求
      next('route')
    } else {
      next()
    }
  }, function getPaidContent (req, res, next) {
    PaidContent.find(function (err, doc) {
      if (err) return next(err)
      res.json(doc)
    })
  })
```

在这个例子中，`getPaidContent` 处理程序将被跳过

，但是任何在 `/a_route_behind_paywall` 路由下的剩余处理程序都会继续执行。

调用 `next()` 和 `next(err)` 表示当前处理程序已完成以及处于什么状态。`next(err)` 将跳过除已设置为处理错误的处理程序之外的所有剩余处理程序链。